#!/bin/bash

case $1 in
    start)
        exec pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
        ;;
    stop)
        exec pg_ctl -D /usr/local/var/postgres stop -s -m fast
        ;;
esac

