#! /bin/bash

HOOKNAME=`basename $0`
SCRIPTSFOLDER="scripts/$HOOKNAME"

# Check if hooks directory is empty
if [ "$(ls $SCRIPTSFOLDER)" ]; then

    for hook in "$SCRIPTSFOLDER/*"; do

        $hook "$@"

        if [[ $? -ne 0 ]]; then
            echo "Hook Failed: $hook"
            exit $?
        fi

    done

fi

